### ISSUE TITLE
Scaffolding Sutil-Safe generates src/Shared/Shared.fs.js

### ISSUE THREAD

**Issue by DejanMilicic** [Jlll1/Sutil-Template#7]
I do not see `src/Shared/Shared.fs.js` within the template,
but it was generated when scaffolding Sutil-Safe

**Comment by Jlll1** [comment]
Hey! Thanks for opening the issue.
This was an embarrassing oversight on my part, this file somehow got into the nuget package that was pushed.
I've pushed a new version (v2.0.1) with that file removed.

Cheers :)
